### ISSUE TITLE
test on carla 0.9.13

### ISSUE THREAD

**Issue by libing64** [jedeschaud/kitti_carla_simulator#2]
# python KITTI_data_generator.py 
Map Town01
Created Actor(id=1669, type=vehicle.tesla.model3)
('Number of spawn points : ', 255)
Spawned 1 vehicles and 1 walkers
Waiting for KITTI to stop ...
KITTI stopped
('Elapsed total time : ', 35.62052607536316)
Traceback (most recent call last):
  File "KITTI_data_generator.py", line 177, in <module>
    main()
  File "KITTI_data_generator.py", line 86, in main
    gen.screenshot(KITTI, world, actor_list, folder_output, carla.Transform(carla.Location(x=0.0, y=0, z=2.0), carla.Rotation(pitch=0, yaw=0, roll=0)))
  File "/home/libing/source/simulator/kitti_carla_simulator/generator_KITTI.py", line 297, in screenshot
    RGB.set_attributes(world.get_blueprint_library())
TypeError: unbound method set_attributes() must be called with RGB instance as first argument (got BlueprintLibrary instance instead)

**Comment by libing64** [comment]
I want use this tools with carla 0.9.13, would you provide some advice to debug or fix this problem?
Great thanks.
